### ISSUE TITLE
Add language pack

### ISSUE THREAD

**Issue by louies0623** [wicknix/SeaLion#5]
Language packs need to be added so that users or developers whose native language is not English can use it.

**Comment by wicknix** [comment]
They don't **need** to be added or supported at all. I speak English. I have no need for anything other than English. If people want other languages supported they are more than welcome to contribute to this project and upload the language packs they want included. Otherwise it will stay English only.

**Comment by louies0623** [comment]
In order to communicate with the developers, they had to use English, and I'm not an English user either.  What I hope is that you can provide the original English .

**Comment by wicknix** [comment]
[Language Packs](https://sourceforge.net/projects/seamonkey-language-packs/files/2.35%20Linux%20language%20packs/)

[Dictionaries](https://addons.thunderbird.net/en-uS/seamonkey/language-tools/)
